accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # accounts C
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('info/', views.info, name='info'),
    path('password/', views.password_change, name='password_change'),
    path('<int:account_pk>/profile/', views.profile, name='profile'),
    path('<int:account_pk>/follow', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/edit_result/', views.update, name='update'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

crud/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')), # 반드시 기존 accounts app 밑에
    path('hashtags/<int:tag_pk>/', views.hashtag, name='hashtag')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings', blank=True)

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
# 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드) 정의

class HashTag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content
    

class Article(models.Model):
    # id : integer 자동으로 정의(Primary Key)
    # id = models.AutoField() -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    # CharField - 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # ImageSpecField : Input 하나만 받고 잘라서 저장
    # ProcessedImageField : Input 받은 것을 처리해서 저장
    # resize to fill : 300 * 300
    # resize to fit : 긴 쪽을 (너비 혹은 높이) 300에 맞추고 비율에 맞게 자름
    image_thumbnail = ImageSpecField(
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 80}
    )

    # DateTimeField
    #     auto_now_add : 생성시 자동으로 저장
    #     auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # settings.AUTH_USER_MODEL : 'accounts.User' (str)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    hashtags = models.ManyToManyField(HashTag, blank=True)

    def __str__(self):
        return f'{self.id}: {self.title}'

# models.py : python 클래스 정의
#           : 모델 설계도
# makemigrations : migration 파일 생성
#                : DB 설계도
# migrate : migration 파일 DB 반영


class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # on_delete
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글을 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 안됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용 x)
    # 4. SET_DEFAULT : 디폴트 값으로 치환

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # User return
        fields = ('username', 'first_name', 'last_name', 'email')

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm

from IPython import embed


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        new_user = CustomUserCreationForm(request.POST)
        if new_user.is_valid():
            user = new_user.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        new_user = CustomUserCreationForm()
    context = {
        'new_user': new_user
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST) # modelform이 아니다
        if form.is_valid():
            # embed()
            # 로그인
            user = form.get_user()
            auth_login(request, user)
            return redirect(request.GET.get('next') or 'articles:index') # 로그인을 하지 않은 상태에서 접근하면 'next'가 None (단축평가)
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:info')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

@login_required
def info(request):
    return render(request, 'accounts/info.html')

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user) # 반드시 첫번째 인자로 user
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def profile(request, account_pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=account_pk)
    context = {
        'user_profile': user
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, account_pk):
    User = get_user_model()
    user_profile = get_object_or_404(User, pk=account_pk)
    # 프로필 주인을 팔로우 한 적이 있으면,
    if user_profile in request.user.followers.all():
        request.user.followers.remove(user_profile)
    # 프로필 주인을 팔로우 하지 않았으면
    else:
        request.user.followers.add(user_profile)
    return redirect('accounts:profile', account_pk)

accounts/templates/accounts/info.html
{% extends 'articles/base.html' %}

{% block body %}
<h3>{{ user.username }}</h3>
<p>{{ user.last_name }} {{ user.first_name }}</p>
<p>{{ user.email }}</p>
<a href="{% url 'accounts:update' %}">정보 수정</a> |
<a href="{% url 'accounts:password_change' %}">비밀번호 변경</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}
{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-secondary">로그인</button>
  {% endbuttons %}
  <a href="{% provider_login_url 'kakao' %}">카카오로 로그인</a>
</form>


{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% load gravatar %}

{% block body %}
<div class="row">
  <div class="col-6">
    <h1 class="text-center">
      <img src="{{ user.email|makehash }}" alt=""> {{ user_profile.username }}의 프로필
    </h1>
  </div>
  <div class="col-6">
    {% with user_profile.followings.all as followings %} 
      {% if user != user_profile %}
          {% if user in followings %}
            <a href="{% url 'accounts:follow' user_profile.pk %}"><i class="far fa-check-circle"></i> unfollow</a>
          {% else %}
            <a href="{% url 'accounts:follow' user_profile.pk %}"><i class="far fa-circle"></i> follow</a>
          {% endif %}
      {% endif %}

    <p class="">팔로워: {{ followings|length }} | 팔로우: {{ user_profile.followers.count }}</p>
    {% endwith %}
  </div>
</div>


{% comment %} 쿼리를 던지는 일을 줄이기 위한 방법 with {% endcomment %}

{% if user == user_profile %}
<div class="container">
  <h2>작성한 글 목록 <sub>({{ user_profile.article_set.count }})</sub></h2>
  {% for article in user_profile.article_set.all %}
  <p><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></p>
  {% endfor %}

  <h2>내가 쓴 댓글 <sub>({{ user_profile.comment_set.count }})</sub></h2>
  {% for comment in user_profile.comment_set.all %}
  <p><a href="{% url 'articles:detail' comment.article.pk %}">{{ comment.article.pk }}번째 글의 {{ comment.content }}</a></p>
  {% endfor %}

  <h2>내가 좋아요 한 글 <sub>({{ user_profile.like_articles.count }})</sub></h2>
  {% for like in user_profile.like_articles.all %}
  <p><a href="{% url 'articles:detail' like.pk %}">{{ like.title }}</a></p>
  {% endfor %}
</div>
{% else %}
  <h3 class="text-center">공개되지 않은 정보입니다.</h3>
{% endif %}
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form new_user %}
  {% buttons %}
    <button type="submit" class="btn btn-secondary">등록</button>
  {% endbuttons %}
</form>


{% endblock %}

accounts/templates/accounts/update.html
{% extends 'articles/base.html' %}
{% load bootstrap4 %}
{% block body %}

<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-secondary">등록</button>
  {% endbuttons %}
</form>

{% endblock %}