accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # accounts C
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('info/', views.info, name='info'),
    path('password/', views.password_change, name='password_change'),
    path('<int:account_pk>/profile/', views.profile, name='profile'),
    path('<int:account_pk>/follow', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    # path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    # path('<int:article_pk>/edit/', views.edit, name='edit'),
    path('<int:article_pk>/edit_result/', views.update, name='update'),
    path('<int:article_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment_delete/<int:comment_pk>/', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
]

crud/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')), # 반드시 기존 accounts app 밑에
    path('hashtags/<int:tag_pk>/', views.hashtag, name='hashtag')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
# 모델(스키마) 정의
# 데이터베이스 테이블을 정의하고,
# 각각의 컬럼(필드) 정의

class HashTag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content
    

class Article(models.Model):
    # id : integer 자동으로 정의(Primary Key)
    # id = models.AutoField() -> Integer 값이 자동으로 하나씩 증가(AUTOINCREMENT)
    # CharField - 필수인자로 max_length 지정
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    # ImageSpecField : Input 하나만 받고 잘라서 저장
    # ProcessedImageField : Input 받은 것을 처리해서 저장
    # resize to fill : 300 * 300
    # resize to fit : 긴 쪽을 (너비 혹은 높이) 300에 맞추고 비율에 맞게 자름
    image_thumbnail = ImageSpecField(
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 80}
    )

    # DateTimeField
    #     auto_now_add : 생성시 자동으로 저장
    #     auto_now : 수정시마다 자동으로 저장
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # settings.AUTH_USER_MODEL : 'accounts.User' (str)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
    hashtags = models.ManyToManyField(HashTag, blank=True)

    def __str__(self):
        return f'{self.id}: {self.title}'

# models.py : python 클래스 정의
#           : 모델 설계도
# makemigrations : migration 파일 생성
#                : DB 설계도
# migrate : migration 파일 DB 반영


class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # on_delete
    # 1. CASCADE : 글이 삭제되었을 때 모든 댓글을 삭제
    # 2. PROTECT : 댓글이 존재하면 글 삭제 안됨.
    # 3. SET_NULL : 글이 삭제되면 NULL로 치환(NOT NULL일 경우 옵션 사용 x)
    # 4. SET_DEFAULT : 디폴트 값으로 치환

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # 위젯 설정 2.
    # title = forms.CharField(
    #     max_length=10, 
    #     label='제목',
    #     widget=forms.TextInput(
    #         attrs={
    #             'placeholder': '제목을 입력바랍니다.'
    #         }
    #     )
    # )
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목을 입력바랍니다.'
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'placeholder': '내용을 입력바랍니다.',
            }
        )
    )
        
    class Meta:
        model = Article
        fields = ('title', 'content', 'image')
        # fields = ('title', )
        # exclude = ('title', )
        # 위젯 설정 1.
        # widgets = {
        #     'title': forms.TextInput(
        #         attrs={
        #             'placeholder': '제목을 입력바랍니다.'
        #         }
        #     )
        # }

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label='댓글',
        widget=forms.Textarea(
            attrs={
                'placeholder': '...댓글댓글댓글댓글...',
                'rows': 3,
            }
        )
    )

    class Meta:
        model = Comment
        fields = ('content', )

# class ArticleForm(forms.Form):
#     title = forms.CharField(
#         max_length=10, 
#         label='제목',
#         widget=forms.TextInput(
#             attrs={
#                 'placeholder': '제목을 입력바랍니다.'
#             }
#         )
#     )
#     content = forms.CharField(
#         # label 내용 수정
#         label='내용',
#         # Django form에서 HTML 속성 지정 -> widget
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': '내용을 입력바랍니다.',
#                 'row': 3,
#                 'col': 30
#             }
#         )
#     )

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied # 오류를 띄울 수 있음
from django.http import HttpResponseForbidden, HttpResponse, JsonResponse
from django.contrib import messages
from IPython import embed

from .models import Article, Comment, HashTag
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-id')
    # embed()
    context = {
        'articles': articles
    }
    # embed()
    return render(request, 'articles/index.html', context)

# def new(request):
#     # if request.method == 'GET':
#     return render(request, 'articles/new.html')
#     # else: # 'POST'
#     #     title = request.POST.get('title')
#     #     content = request.POST.get('content')
#     #     article = Article(title=title, content=content)
#     #     article.save()
#     #     return redirect('articles:detail', article.pk)

@login_required
def create(request):
    # 저장 로직
    if request.method == 'POST':
    # POST 요청 -> 검증 및 저장
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        article_form = ArticleForm(request.POST, request.FILES)
        # embed()
        # 검증
        if article_form.is_valid():
        # 검증에 성공하면 저장하고,
            # title = article_form.cleaned_data.get('title')
            # content = article_form.cleaned_data.get('content')
            # article = Article(title=title, content=content)
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            # 해시태그 저장 및 연결 작업
            sep = article.content.split()
            for idx, word in enumerate(sep):
                if word.startswith('#'):
                    # if HashTag.objects.filter(content=word).exists():
                    #     tag = HashTag.objects.get(content=word)
                    # else:
                    #     tag = HashTag.objects.create(content=word)
                    # article.hashtags.add(tag)
                    hashtag, created = HashTag.objects.get_or_create(content=word)
                    article.hashtags.add(hashtag)
                    # (오브젝트, 만들어진 것인지 가져온 것인지)

            messages.success(request, '새로운 글이 등록되었습니다.')
            # redirect
            return redirect('articles:detail', article.pk)
        # else:
        #     다시 폼으로 들아가! -> 중복돼서 제거!
    # context = {
    #     'article': article
    # }
    # return render(request, 'articles/create.html', context)
    # embed()
    else:
    # GET 요청 -> Form
        article_form = ArticleForm()
    # GET -> 비어있는 Form conte    xt
    # POST -> 검증 실패시 에러메세지와 입력값 채워진 Form context
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)

def detail(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    comment = article.comment_set.all().order_by('-pk')
    comment_form = CommentForm()
    context = {
        'article': article,
        'comments': comment,
        'comment_form': comment_form,
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        article.delete()
        return redirect('articles:index')
    else:
        messages.warning(request, '삭제할 권한이 없습니다.')
        raise PermissionDenied
        # return redirect('articles:detail', article_pk)
    # tmp = article.title
    # article.delete()
    # context = {
    #     'delete_tmp': tmp
    # }
    # return render(request, 'articles/delete.html', context)

# def edit(request, article_pk):
#     article = Article.objects.get(pk=article_pk)
#     context = {
#         'article': article
#     }
#     return render(request, 'articles/edit.html', context)

def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            article_form = ArticleForm(request.POST, instance=article)
            if article_form.is_valid() and article_form.has_changed():
                article = article_form.save()
                messages.success(request, '글이 수정되었습니다.')
                #-----------------------------------------------------------------------
                # 해시태그 수정
                article.hashtags.clear()
                for word in article.content.split():
                    if word.startswith('#'):
                        hashtag, created = HashTag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                #-----------------------------------------------------------------------
                return redirect('articles:detail', article_pk)
            else:
                messages.warning(request, '수정할 내용이 없습니다.')
        else:
            article_form = ArticleForm(instance=article)
        context = {
            'article_form': article_form,
        }
        return render(request, 'articles/form.html', context)
    else:
        messages.warning(request, '수정할 권한이 없습니다.')
        raise PermissionDenied # 403 error
        # return redirect('articles:detail', article_pk)

@require_POST
def comment_create(request, article_pk):
    if request.user.is_authenticated:
        # 1. modelform에 사용자 입력값 넣고
        comment_form = CommentForm(request.POST)
        # 2. 검증하고,
        if comment_form.is_valid():
        # 3. 맞으면 저장!
            # 3-1. 사용자 입력값으로 comment instance 생성(저장은 X)
            comment = comment_form.save(commit=False)
            # 3-2. FK 넣고 저장
            comment.article_id = article_pk
            comment.user = request.user
            comment.save()
        # comment = Comment.objects.create(content=content, article_id=article_pk)
            messages.success(request, '댓글이 등록되었습니다.')
        else:
            messages.warning(request, '댓글 작성에 실패하였습니다.')
        # 4. return redirect
        return redirect('articles:detail', article_pk)
    else:
        return HttpResponse('Unautherized', status=401)

@login_required
@require_POST
def comment_delete(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
        messages.info(request, '댓글이 삭제되었습니다.')
    else:
        messages.warning(request, '권한이 없습니다.')
        return HttpResponseForbidden() # 권한이 없습니다.
    return redirect('articles:detail', article_pk)

@login_required
def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user
    is_liked = True
    if user in article.like_users.all():
        article.like_users.remove(user)
        is_liked = False
    else:
        article.like_users.add(user)
        is_liked = True
    like_count = article.like_users.count()
    return JsonResponse({'is_liked': is_liked, 'like_count': like_count})

def hashtag(request, tag_pk):
    hashtag = get_object_or_404(HashTag, pk=tag_pk)
    context = {
        'hashtag': hashtag
    }
    return render(request, 'articles/hashtag.html', context)

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>게시판</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> {% endcomment %}
  <link href="https://fonts.googleapis.com/css?family=Poor+Story&display=swap" rel="stylesheet">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
  <link rel="shortcut icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  <style>
    body {
      font-family: "Poor Story", "sans serif"
    }
    a {
      color: rgb(138, 138, 138);
      text-decoration: none;
    }
    footer {
      display: fixed;
      bottom: 0;
      margin: 10 0 0 0;
      height: 50px;
      width: 100%;
    }
    .time_cnu {
      font-size: 0.8rem;
    }
    
  </style>
  {% block css %}
  {% endblock %}
</head>
<body>
  {% include '_navbar.html' %}
  <div class="container">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    
    {% block body %}
    {% endblock %}
  </div>
  <footer class="bg-dark text-light mb-0 mt-3 d-flex justify-content-between align-items-center px-3">
    <div class="d-inline-block">조선행</div>
    <a href="#" class="d-inline-block">위로!<i class="fas fa-angle-up"></i></a>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src={% static "bootstrap/js/bootstrap.min.js" %}></script>
  <script src="https://kit.fontawesome.com/e2e473e5eb.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  {% block script %}
  {% endblock %}
</body>
</html>

articles/templates/articles/create.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>{{ article.id }}번째 글이 작성되었습니다.</h1>
  <a href="{% url 'articles:index' %}">Home</a>
{% endblock %}

articles/templates/articles/delete.html
{% extends 'articles/base.html' %}

{% block body %}
<h1>{{ delete_tmp }} 글이 삭제되었습니다.</h1>
<a href="{% url 'articles:index' %}">목록으로</a>
{% endblock %}

articles/templates/articles/detail.html
{% extends 'articles/base.html' %}

{% load static %}
{% load bootstrap4 %}

{% block body %}
<h1>{{ article.title }}</h1>
<h4 class="text-right">{{ article.id }}번째 글</h4>

<div class="lead d-inline-block" style="width:100%;">
  {% if article.image %}
  <img src="{{ article.image.url }}" alt="{{ article.image.name }}">
  <br>
  {% endif %}
  {% load hashtag %}
  <p>{{ article|make_link|safe }}</p>
  <p  class="text-center"><sub id="like-count">좋아요: {{ article.like_users.count }}</sub></p>
  
  <div class="d-inline-block text-center" style="width: 100%;">
    {% if user in article.like_users.all %}
    <i id="like-button" data-id="{{ article.id }}" class="fas fa-heart text-danger animated infinite pulse delay-1s"></i>
    {% else %}
    <i id="like-button" data-id="{{ article.id }}" class="far fa-heart text-danger animated infinite rubberBand delay-1s"></i></i>
    {% endif %}
  </div>
</div>

<p class="text-right">글쓴이 : <a href="{% url 'accounts:profile' article.user.pk %}">{{ article.user }}</a></p>
<p class="text-right time_cnu">작성일자: {{ article.created_at }}</p>
<p class="text-right time_cnu">최종 수정일자: {{ article.updated_at }}</p>
<a href="{% url 'articles:index' %}">목록으로</a>
{% if user == article.user %}
<a href="{% url 'articles:update' article.pk %}">수정</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST" onclick="return confirm('진짜 지울래?')">
  {% csrf_token %}
  <input type="submit" value="삭제">
</form>
{% endif %}
<hr>
{% if user.is_authenticated %}
<h4>댓글 작성</h4>
{% endif %}
<p>댓글 수: {{ comments.count }}</p>
{% if user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}", method="POST">
  {% csrf_token %}
  {% bootstrap_form comment_form %}
  {% buttons %}
    <button type="submit" class="btn btn-secondary">등록</button>
  {% endbuttons %}
</form>
<hr>
{% endif %}
{% for comment in comments %}
<p>{{ comment.content }}</p>
<p><sub>작성자 : {{ comment.user }}</sub></p>
<p><sub>{{ comment.created_at }}</sub></p>
{% if user == comment.user %}
<form action="{% url 'articles:comment_delete' article.pk comment.pk %}", method="POST">
  {% csrf_token %}
  <input type="submit" value="삭제?">
</form>
{% endif %}
<br>
{% empty %} <!-- 비어있는 경우에는 if문 사용하지 않아도 표현 가능! -->
<p>댓글이 없어요! T^T</p>
<br>
{% endfor%}
{% endblock %}

{% block script %}
<script>
  const likeButton = document.querySelector('#like-button')
  const likeCount = document.querySelector('#like-count')
  likeButton.addEventListener('click', function(event) {
    console.log(event.target.dataset.id)
    axios.get(`/articles/${event.target.dataset.id}/like/`)
      .then(response => {
        console.log(response)
        console.log(event.target)
        if (response.data.is_liked) {
          event.target.classList.remove('far')
          event.target.classList.add('fas')
        } else {
          event.target.classList.remove('fas')
          event.target.classList.add('far')
        }
        console.log(likeCount)
        likeCount.innerText = `좋아요: ${response.data.like_count}`
        
      })
  })
</script>
{% endblock %}

articles/templates/articles/edit.html
{% extends 'articles/base.html' %}

{% block css %}
<style>
  input, textarea, label {
    margin-bottom: 10px;
  }

  label {
    display: inline-block;
  }
</style>
{% endblock %}

{% block body %}
{% comment %} <form action="{# url 'articles:update' article.pk #}" method="POST">
  {% csrf_token %}
  <div class="form-group">
    <label for="title">제목</label>
    <input type="text" name="title" class="form-control" id="title" aria-describedby="emailHelp" value="{{ article.title }}">
  </div>
  <div class="form-group">
    <label for="text">내용</label>
    <textarea class="form-control" id="text" name="text" rows="3">{{ article.content }}</textarea>
  </div>
  <button type="submit" class="btn btn-secondary">수정</button>
  <a href="{% url 'articles:detail' article.pk %}"><button type="button" class="btn btn-secondary">취소</button></a>
</form> {% endcomment %}

<form action="" method="POST">
  {% csrf_token %}
  {{ article_form.as_p }}
  <button type="submit" class="btn btn-secondary">수정</button>
  <a href="{% url 'articles:detail' article.pk %}"><button type="button" class="btn btn-secondary">취소</button></a>
</form>
{% endblock %}

articles/templates/articles/form.html
{% extends 'articles/base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block body %}
{% if request.resolver_match.url_name == 'create' %}
    <h1>글 작성하기</h1>
{% else %}
    <h1>글 수정하기</h1>
{% endif %}
<form action="" method="POST" class='form' enctype='multipart/form-data'>
  {% csrf_token %}
  {% bootstrap_form article_form %}
  {% buttons %}
    <button type="submit" class="btn btn-secondary">등록</button>
  {% endbuttons %}
</form>
{% endblock body %}

articles/templates/articles/hashtag.html
{% extends 'articles/base.html' %}

{% block body %}

<h1>{{ hashtag.content }}</h1>
{% for article in hashtag.article_set.all %}
<h3><a href="{% url 'articles:detail' article.pk %}">
        {% if article.image %}
            <img src="{{ article.image_thumbnail.url }}" alt="">
        {% else %}
            {{ article.title }}
        {% endif %}
    </a>
</h3>
{% endfor %}

{% endblock %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'articles/style.css' %}">

{% endblock %}
{% block body %}
  <div class="d-flex justify-content-center">
    <img src="{% static 'articles/bg.jpg' %}" alt="스폰지밥">
  </div>
  <h1 class="text-center title">게시판에 오신 것을 환영합니다.</h1>
  {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}" class="btn btn-secondary mt-3">글 작성하기</a>
  {% endif %}
  <table class="table mt-3">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">제목</th>
      <th scope="col">작성일자</th>
      <th scope="col">수정일자</th>
    </tr>
  </thead>
  <tbody>
  {% for article in articles %}
    <tr>
      <th scope="row">{{ article.id }}</th>
      <td class="title"><a href="{% url 'articles:detail' article.pk %}">{{ article.title }} 
      {% if article.comment_set.count != 0 %}
      <sub>({{ article.comment_set.count }})</sub>
      {% endif %}
      </a></td>
      <td class="time_cnu">{{ article.created_at }}</td>
      <td class="time_cnu">{{ article.updated_at }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

articles/templates/articles/new.html
{% extends 'articles/base.html' %}
{% block body %}
  <h1>새로운 글 작성</h1>
  {% comment %} <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">제목</label>
      <input type="text" name="title" class="form-control" id="title" aria-describedby="emailHelp" placeholder="제목을 입력하세요.">
    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" id="content" name="content" rows="3" placeholder="내용을 입력해주세요."></textarea>
    </div>
    <button type="submit" class="btn btn-secondary">등록</button>
    <a href="{% url 'articles:index' %}"><button type="button" class="btn btn-secondary">취소</button></a>
  </form> {% endcomment %}

  <form action="" method="POST">
    {% csrf_token %}
    {{ article_form.as_p }}
    <button type="submit" class="btn btn-secondary">등록</button>
  </form>
{% endblock %}